name: wangxin.io deploy
on:
  push:
    branches:
    - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Clean
        uses: heowc/action-hexo@master
        with:
          args: clean
      - name: Generate
        uses: heowc/action-hexo@master
        with:
          args: generate
      - name: Set env
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
        run: |
          git config --global user.name 'Xin Wang'
          git config --global user.email 'xin.victorwang@gmail.com'
          sed -i "s/GITHUB_ACCESS_TOKEN/$GITHUB_ACCESS_TOKEN/g" ./_config.yml
      - name: Deploy
        uses: heowc/action-hexo@master
        env:
          EMAIL: xin.victorwang@gmail.com
          NAME: Xin Wang
        with:
          args: deploy
