name: wangxin.io deploy
on:
  push:
    branches:
    - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Clean
        uses: heowc/action-hexo@master
        with:
          args: clean
      - name: Generate
        uses: heowc/action-hexo@master
        with:
          args: generate
      - name: Deploy
        uses: heowc/action-hexo@master
        env:
          EMAIL: xin.victorwang@gmail.com
          NAME: Xin Wang
        with:
          args: deploy
